name: stream_typewriter_text
description: "A new Flutter plugin project."
version: 1.0.0
repository: https://github.com/hantrungkien/stream-typewriter-text
maintainer: KienHT

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: