name: stream_typewriter_text
description: "Stream Typewriter Text is a Flutter package that provides a typewriter text animation effect."
version: 1.0.3
repository: https://github.com/hantrungkien/stream-typewriter-text
maintainer: KienHT

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: